// Generated by scripts/build-i18n.mjs from openhanako zh-TW.json (Apache-2.0). Do not edit.
return (function () {
  const D = {
    "sidebar.title": "對話",
    "sidebar.newChat": "新對話",
    "sidebar.collapse": "收起側邊欄",
    "sidebar.toggle": "側邊欄",
    "sidebar.jian": "書桌",
    "sidebar.bridgeShort": "接入",
    "sidebar.activity": "助手活動",
    "automation.title": "任務計畫",
    "skills.panel.title": "Skills",
    "settings.title": "設定",
    "welcome.memoryOn": "記憶",
    "welcome.memoryOff": "此次聊天不參考記憶",
    "welcome.memoryDisabled": "記憶已關閉",
    "welcome.messages": [
      "要做什麼，交給 {name} 吧",
      "今天想聊點什麼？",
      "{name} 隨時都在",
      "有什麼需要幫忙的嗎？",
      "想到什麼就說什麼吧～"
    ],
    "input.attachFiles": "新增檔案",
    "input.commandMenu": "命令選單",
    "input.selectWorkspace": "選擇工作台",
    "input.workspace": "工作台：",
    "input.placeholder": "說點什麼...",
    "chat.send": "傳送",
    "chat.steer": "插話",
    "chat.stop": "停止",
    "desk.jianLabel": "箋",
    "desk.title": "書桌",
    "rightWorkspace.tabs.sessionFiles": "對話檔案",
    "rightWorkspace.tabs.workspace": "工作台",
    "rightWorkspace.tabs.label": "右側工作台",
    "rightWorkspace.jian.expand": "展開箋",
    "rightWorkspace.jian.collapse": "收起箋",
    "titlebar.currentChatTitle": "目前對話標題",
    "session.untitled": "新對話",
    "common.loading": "載入中...",
    "preview.toggle": "預覽面板",
    "error.llmEmptyResponse": "模型返回了空响应",
    "error.llmAuthFailed": "模型认证失败",
    "sidebar.empty": "還沒有對話哦 ✿",
    "rightWorkspace.sessionFiles.empty": "本對話還沒有產生或上傳檔案",
    "desk.jianPlaceholder": "寫點什麼，告訴助手這個資料夾裡面的檔案該如何處理..."
  };
  function t(key, vars) {
    let v = D[key];
    if (Array.isArray(v)) v = v[Math.floor(Math.random() * v.length)];
    if (typeof v !== 'string') return key;
    if (vars) for (const [k, val] of Object.entries(vars)) v = v.replaceAll('{' + k + '}', String(val));
    return v;
  }
  return { t, raw: D };
})();
