// Emit js/lib/i18n.js from upstream locale JSON (Apache-2.0) so on-screen copy
// matches openhanako exactly instead of being re-translated by hand.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

const UP = process.env.OPENHANAKO_SRC || '/tmp/openhanako-full/desktop/src';
const LOCALE = process.env.HANA_LOCALE || 'zh-TW';
const here = dirname(new URL(import.meta.url).pathname);
const dict = JSON.parse(readFileSync(join(UP, 'locales', `${LOCALE}.json`), 'utf8'));

const KEYS = [
  'sidebar.title', 'sidebar.newChat', 'sidebar.collapse', 'sidebar.toggle', 'sidebar.jian',
  'sidebar.bridgeShort', 'sidebar.activity', 'automation.title', 'skills.panel.title',
  'settings.title', 'welcome.memoryOn', 'welcome.memoryOff', 'welcome.memoryDisabled',
  'welcome.messages', 'input.attachFiles', 'input.commandMenu', 'input.selectWorkspace',
  'input.workspace', 'input.placeholder', 'chat.send', 'chat.steer', 'chat.stop',
  'desk.jianLabel', 'desk.title', 'rightWorkspace.tabs.sessionFiles',
  'rightWorkspace.tabs.workspace', 'rightWorkspace.tabs.label', 'rightWorkspace.jian.expand',
  'rightWorkspace.jian.collapse', 'titlebar.currentChatTitle', 'chat.you', 'session.untitled',
  'sidebar.noSessions', 'common.loading', 'preview.toggle', 'chat.assistant', 'chat.system',
  'error.llmEmptyResponse', 'error.llmAuthFailed', 'sidebar.empty', 'rightWorkspace.sessionFiles.empty', 'desk.jianPlaceholder',
];

// Upstream locale files mix literal dotted keys ("preview.toggle") with nested
// objects, so resolve the flat key first and fall back to walking the path.
const pick = (path) => {
  if (Object.prototype.hasOwnProperty.call(dict, path)) return dict[path];
  return path.split('.').reduce(
    (cur, k) => (cur && typeof cur === 'object' ? cur[k] : undefined),
    dict,
  );
};
const table = {};
for (const k of KEYS) {
  const v = pick(k);
  if (v !== undefined && v !== null) table[k] = v;
}

const out = `// Generated by scripts/build-i18n.mjs from openhanako ${LOCALE}.json (Apache-2.0). Do not edit.
return (function () {
  const D = ${JSON.stringify(table, null, 2).replace(/\n/g, '\n  ')};
  function t(key, vars) {
    let v = D[key];
    if (Array.isArray(v)) v = v[Math.floor(Math.random() * v.length)];
    if (typeof v !== 'string') return key;
    if (vars) for (const [k, val] of Object.entries(vars)) v = v.replaceAll('{' + k + '}', String(val));
    return v;
  }
  return { t, raw: D };
})();
`;
writeFileSync(resolve(here, '../js/lib/i18n.js'), out);
console.log(`lib/i18n.js: ${Object.keys(table).length} keys from ${LOCALE}`);
