// Deterministically build style.css from upstream openhanako sources (Apache-2.0).
// Upstream: https://github.com/liliMozi/openhanako
// No hand-written approximations: real files are concatenated verbatim,
// with fonts/textures inlined and `body`/`html` selectors scoped to the shell root.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';

const UP = process.env.OPENHANAKO_SRC || '/tmp/openhanako-full/desktop/src';
const OUT = resolve(dirname(new URL(import.meta.url).pathname), '../js/style.css');
const ROOT = '.hana-replica';

const read = (p) => readFileSync(join(UP, p), 'utf8');

// Upstream declares 521 @font-face rules over 111 unique .woff2 files, so
// inlining data URIs per face would duplicate ~40 MiB. Instead emit each file
// once and let the shell turn it into a blob: URL at runtime.
const fontFiles = new Map();
function externalizeFonts(css) {
  return css.replace(/url\(['"]\.\/fonts\/([^'"]+)['"]\)/g, (m, file) => {
    const p = join(UP, 'themes/fonts', file);
    if (!existsSync(p)) throw new Error(`missing font: ${file}`);
    if (!fontFiles.has(file)) fontFiles.set(file, readFileSync(p).toString('base64'));
    return `url('__HANA_FONT__${file}__')`;
  });
}

function inlineTextures(css) {
  return css.replace(/url\((['"]?)\.\/assets\/textures\/([^)'"]+)\1\)/g, (m, q, file) => {
    const p = join(UP, 'assets/textures', file);
    if (!existsSync(p)) throw new Error(`missing texture: ${file}`);
    const mime = file.endsWith('.png') ? 'image/png' : 'application/octet-stream';
    return `url("data:${mime};base64,${readFileSync(p).toString('base64')}")`;
  });
}

// Scope document-level selectors to the shell root so the bundle cannot
// restyle the surrounding Studio chrome. Structure/values stay upstream.
function scope(css) {
  return css
    .replace(/(^|[\s,])body(?=[.#:[\s,{>])/g, `$1${ROOT}`)
    .replace(/(^|[\s,])body(?=\s*\{)/g, `$1${ROOT}`)
    .replace(/html(\[[^\]]+\])?\s+body/g, (m, attr) => `${ROOT}${attr || ''}`)
    .replace(/(^|[\s,])html(?=\s*\{)/g, `$1${ROOT}`);
}

const parts = [];
parts.push(`/* Ported from openhanako (Apache-2.0): https://github.com/liliMozi/openhanako
   Generated by plugins/openhanako-shell/scripts/build-css.mjs — do not edit by hand. */`);

// 1. Keyframes.
parts.push(read('animations.css'));

// 2. Global stylesheet, minus the two @import lines resolved above.
const globals = read('styles.css').replace(/^@import url\([^)]+\);\s*$/gm, '');
parts.push(scope(inlineTextures(globals)));

// 3. Active theme.
parts.push(read('themes/new-warm-paper.css'));

// 4. CSS modules: upstream hashes class names per module; the shell uses the
//    raw class names, so module rules are appended verbatim.
const MODULES = [
  'react/components/Welcome.module.css',
  'react/components/chat/Chat.module.css',
  'react/components/shared/AttachmentChip.module.css',
  'react/components/SessionList.module.css',
  'react/components/input/InputArea.module.css',
  'react/components/right-workspace/RightWorkspacePanel.module.css',
  'react/components/right-workspace/SessionStatusCard.module.css',
  'react/components/right-workspace/SessionTodoCard.module.css',
  'react/components/notices/SidebarNoticeSlot.module.css',
  'react/components/StatusBar.module.css',
];
for (const m of MODULES) {
  parts.push(`/* upstream ${basename(m)} */\n${scope(inlineTextures(read(m)))}`);
}

// 5. Host adapter: only what the WASM host needs that a browser bundler
//    would otherwise provide (root box, slot collapsing).
parts.push(readFileSync(
  join(dirname(new URL(import.meta.url).pathname), 'host-adapter.css'), 'utf8'));

const css = parts.join('\n\n');
writeFileSync(OUT, css);

// Companion module: the upstream @font-face block plus one base64 payload per
// unique font file. Kept out of style.css because the host injects that asset
// verbatim, while these `__HANA_FONT__<file>__` placeholders must first be
// swapped for blob: URLs at runtime (521 faces over 111 files: inlining data
// URIs per face would repeat the same payloads for ~40 MiB).
const faces = externalizeFonts(read('themes/new-warm-paper-fonts.css'));
const FONTS_OUT = resolve(dirname(new URL(import.meta.url).pathname), '../js/lib/fonts.js');
const entries = [...fontFiles]
  .map(([file, data]) => `  ${JSON.stringify(file)}: ${JSON.stringify(data)},`)
  .join('\n');
writeFileSync(FONTS_OUT, `// Generated by scripts/build-css.mjs from openhanako (Apache-2.0). Do not edit.
// Upstream @font-face rules + one base64 woff2 payload per unique font file.
return {
  faces: ${JSON.stringify(faces)},
  files: {
${entries}
  },
};
`);

const faceCount = (faces.match(/@font-face/g) || []).length;
const mib = (n) => (n / 1048576).toFixed(2);
console.log(`style.css:  ${css.length.toLocaleString()} chars (${mib(css.length)} MiB)`);
console.log(`lib/fonts.js: ${faceCount} @font-face`);
console.log(`lib/fonts.js: ${fontFiles.size} unique woff2 (${mib([...fontFiles.values()].reduce((n, s) => n + s.length, 0))} MiB base64)`);
